{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migration-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: "{{ .Values.migrations.image }}:{{ .Values.migrations.tag }}"
          envFrom:
            - configMapRef:
                name: laravel-config
            - secretRef:
                name: laravel-secrets
          env:
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          command:
            - php
            - artisan
            - migrate
            - --force
{{- end }}
