apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Values.namespace }}
  labels:
    app: laravel
    tier: backend
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
spec:
  selector:
    app: laravel
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
