apiVersion: v1
kind: Service
metadata:
  name: laravel-nginx-service
  namespace: {{ .Values.namespace }}
  labels:
    app: laravel
    tier: frontend
    {{- include "laravel-vue-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP  # CHANGED FROM NodePort TO ClusterIP (for Ingress)
  selector:
    app: laravel
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
